"""Plain-language per-test interpretation text (source-verified, no patient data)."""

# Each: (what it checks, note when normal, note when low, note when high).
INFO = {
    "creatinine": ("A waste product your kidneys filter out.", "Kidneys are clearing waste well.", "", "May mean the kidneys filter a bit slower."),
    "gfr": ("How fast your kidneys filter blood.", "Excellent kidney filtering.", "", "Reduced kidney filtering."),
    "urea": ("Nitrogen waste from protein.", "Within healthy limits.", "", "Can mean dehydration or kidney strain."),
    "uric_acid": ("A breakdown product that can form crystals.", "Normal.", "", "High can cause gout or kidney stones."),
    "ast": ("An enzyme released when liver cells are irritated.", "Liver looks happy.", "", "Some liver irritation."),
    "alt": ("A liver-specific enzyme.", "Liver looks happy.", "", "Some liver irritation."),
    "ast_alt_ratio": ("The balance between two liver enzymes.",
        "A healthy balance.", "",
        "By itself this ratio rarely matters when both enzymes are normal."),
    "ggtp": ("An enzyme from the liver's bile tubes.", "Bile flow is fine.", "", "May hint at bile-flow or alcohol-related stress."),
    "alp": ("An enzyme from liver and bone.", "Normal.", "", "Liver or bone activity."),
    "bili_total": ("A yellow pigment from broken-down red cells.", "Cleared normally.", "", "May point to bile-flow or red-cell issue."),
    "bili_direct": ("Bilirubin already processed by the liver.", "Normal.", "", "Bile-flow concern."),
    "protein_total": ("All the protein in your blood.", "Good protein reserves.", "", "Often just dehydration; sometimes liver/kidney loss."),
    "albumin": ("The main protein your liver makes.", "Good nutrition and liver output.", "", "May mean low intake, or liver/kidney loss."),
    "globulin": ("Proteins tied to immunity and transport.", "Normal immune proteins.", "", "May reflect immune activity."),
    "ag_ratio": ("The balance of two protein types.", "Balanced.", "", "A mild imbalance - review with the proteins."),
    "amylase": ("An enzyme from the pancreas and saliva.", "Normal.", "",
        "Mildly raised; under 3x the limit alone rarely means pancreatitis."),
    "calcium": ("A mineral for bones and nerves.", "Normal.", "Low: check parathyroid/vitamin D.", "High: check parathyroid or vitamins."),
    "phosphorus": ("A mineral for bones and cells.", "Normal.", "",
        "Mildly high; with good kidneys this is usually diet or harmless."),
    "sodium": ("The salt that controls your body's water.", "Balanced.", "Very mildly low - usually hydration.", "Often dehydration."),
    "potassium": ("A salt that keeps your heart and muscles working.", "Balanced.", "Can affect the heartbeat.", "Can affect the heartbeat."),
    "chloide": ("A salt that helps balance acids.", "Balanced.", "", "Usually tracks sodium shifts."),
    "chol_total": ("All the cholesterol in your blood.", "Desirable (under 200).", "", "Slightly above the ideal."),
    "triglycerides": ("Blood fat from the calories you eat.", "Desirable (under 150).", "", "High - cut sugars and alcohol."),
    "hdl": ("'Good' cholesterol that clears arteries.", "Protective for the heart.", "Lower side - raise with exercise/healthy fats.", ""),
    "ldl": ("'Bad' cholesterol that furs up arteries.", "Ideal (under 100).", "", "Above ideal - a heart-risk marker worth a chat with your doctor."),
    "vldl": ("Carriers of blood fat.", "Normal.", "", "Tracks with triglycerides."),
    "non_hdl": ("All the 'bad' cholesterol combined.", "Ideal (under 130).", "", "Above ideal - reflects overall heart risk."),
    "hba1c": ("Your average blood sugar over 3 months.", "Healthy, non-diabetic range.", "", "Prediabetes range."),
    "eag": ("Estimated average blood sugar from HbA1c.", "For context only.", "", ""),
    "glucose_f": ("Your blood sugar after fasting.", "Normal fasting sugar.", "Low blood sugar.", "Prediabetes/diabetes range."),
    "hscrp": ("A measure of low-grade inflammation and heart risk.", "Low heart risk.", "", "Average to high heart risk."),
    "apo_a1": ("The protein in 'good' cholesterol.", "Healthy level.", "Less heart protection.", ""),
    "apo_b": ("The protein in 'bad' cholesterol.", "Normal.", "", "Higher plaque risk."),
    "apo_ratio": ("The balance of bad-to-good cholesterol proteins.", "Desirable (under 0.98).", "", "Raises heart-disease risk."),
    "hemoglobin": ("The oxygen-carrying part of blood.", "No anaemia.", "Anaemia - can cause tiredness; check iron/B12.", "Thick blood or dehydration."),
    "pcv": ("How much of your blood is red cells.", "Normal.", "Can mean anaemia or bleeding.", "Often dehydration."),
    "rbc": ("Number of red blood cells.", "Normal.", "Slightly low - may point to early iron lack.", "Too many cells."),
    "mcv": ("Average size of red cells.", "Normal size.", "Small cells hint at iron lack.", "Large cells hint at B12/folate lack."),
    "mch": ("Haemoglobin inside each red cell.", "Normal.", "Pale cells hint at iron lack.", ""),
    "mchc": ("How concentrated the haemoglobin is.", "Normal.", "Low colour often means iron lack.", ""),
    "rdw": ("How mixed in size the red cells are.", "Even-sized cells.", "", "Mixed sizes often mean iron lack."),
    "tlc": ("Total white blood cells.", "Normal immunity.", "Lower immunity.", "Active infection or inflammation."),
    "neutrophils": ("White cells that fight bacteria.", "Normal.", "Lower resistance to infection.", "Bacterial infection or inflammation."),
    "lymphocytes": ("White cells that fight viruses.", "Normal.", "Lower immunity.", "Slightly raised - often a recent mild virus, usually harmless."),
    "monocytes": ("White cells that clean up.", "Normal.", "", "Slightly raised - often recovery/inflammation, usually temporary."),
    "eosinophils": ("White cells linked to allergies.", "Normal.", "", "Allergy or parasite activity."),
    "basophils": ("White cells that signal allergy.", "Normal.", "", "Allergic or inflammatory activity."),
    "platelets": ("Cells that help blood clot.", "Normal clotting.", "Bleeding risk.", "Clot tendency."),
    "mpv": ("Average size of platelets.", "Normal.", "", "Larger, newer platelets."),
    "esr": ("A general inflammation marker.", "No significant inflammation.", "", "Some inflammation present."),
    "vit_b12": ("A vitamin for nerves and blood cells.", "Adequate.", "Low - can affect nerves and blood cells.", ""),
    "vit_d": ("A vitamin for bones and immunity.", "Sufficient.", "Low - weaker bones and immunity; common and fixable.", "Toxic range."),
    "iron": ("Iron circulating in your blood.", "Normal.", "Low iron stores.", "Excess iron."),
    "tibc": ("How hard your body is working to carry iron.", "Normal.", "High often means iron shortage.", "Low can mean inflammation."),
    "transf_sat": ("How full your iron transport is.", "Normal.", "Under 20% means low usable iron - an early iron shortage.", ""),
    "t3_free": ("The active thyroid hormone.", "Balanced.", "Overactive thyroid.", "Underactive thyroid."),
    "t4_free": ("The main thyroid hormone.", "Balanced.", "Overactive thyroid.", "Underactive thyroid."),
    "tsh": ("The signal that controls your thyroid.", "Balanced thyroid.", "Overactive thyroid.", "Underactive thyroid."),
    "ur_sp_grav": ("How concentrated your urine is.", "Well hydrated.", "", ""),
    "ur_ph": ("How acidic your urine is.", "Normal range.", "", ""),
    "ur_protein": ("Protein leaking into urine.", "None - healthy.", "", "Present - worth a kidney check."),
    "ur_glucose": ("Sugar spilling into urine.", "None - normal.", "", "Sugar present - check blood sugar."),
    "ur_ketones": ("Fat-burn byproducts in urine.", "None - normal.", "", "Present - fasting or possible diabetes."),
    "ur_bili": ("Bile pigment in urine.", "None - normal.", "", "Present - liver/bile check."),
    "ur_blood": ("Blood in urine.", "None - normal.", "", "Trace - urinary tract check."),
    "ur_le": ("White-cell enzyme in urine.", "None - normal.", "", "Present - possible urine infection."),
    "ur_nitrite": ("A bacteria marker in urine.", "None - normal.", "", "Present - possible urine infection."),
    "ur_uro": ("Bilirubin breakdown in urine.", "Normal.", "", "Raised - liver/red-cell check."),
}


def note_for(key: str, status: str) -> str:
    what, normal, low, high = INFO.get(key, ("", "", "", ""))
    return {"normal": normal, "low": low, "high": high,
            "info": normal, "flag": high}.get(status, normal) or normal
